# Generated by Django 4.0 on 2024-10-02 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 3, 12, 27, 59, 8406, tzinfo=utc)),
        ),
    ]
