# Generated by Django 4.0 on 2024-10-14 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailverification_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 15, 12, 56, 40, 27036, tzinfo=utc)),
        ),
    ]
